(* don't remove the following line, it makes the tests much easier to express *)
open BoolExpr

let test1 = (token_of_string "or" = OR)
let test2 = (token_of_string "not" = NOT)
let test3 = (token_of_string "xor" = XOR)
let test4 = (token_of_string "=" = EQ)
let test5 = (parse_bool_exp [OP; AND; OP; OR; CONST false; CONST false; CP; OP; NOT; CONST true; CP; CP] = And (Or (Const false, Const false), Not (Const true)))
let test6 = (parse_bool_exp [OP; EQ; OP; OR; VAR "x"; CONST true; CP; CONST false; CP] = Eq (Or (Id "x", Const true), Const false))
let test7 = (parse_bool_exp [OP; AND; OP; XOR; CONST false; CONST false; CP; OP; NOT; CONST true; CP; CP] = And (Xor (Const false, Const false), Not (Const true)))
let test8 = (parse_bool_exp [OP; XOR; OP; AND; CONST true; CONST false; CP; OP; AND; CONST true; CONST true; CP; CP] = Xor (And (Const true, Const false), And (Const true, Const true)))
let test9 = (eval_bool_exp (And (Or (Const false, Const false), Not (Const true))) [] = false)
let test10 = (eval_bool_exp (Eq (Or (Id "x", Const true), Const false)) [] = false)
let test11 = (eval_bool_exp (And (Xor (Const false, Const false), Not (Const true))) [] = false)
let test12 = (eval_bool_exp (Xor (And (Const true, Const false), And (Const true, Const true))) [] = true)
let test13 = (subsets [2] = [[]; [2]])
let test14 = (subsets ["c";"a"] = [[]; ["a"]; ["c"]; ["c";"a"]])
let test15 = (subsets [1;4] = [[]; [1]; [4]; [1;4]])
let test16 = (subsets [5; 1] = [[]; [1]; [5]; [5; 1]])
let test17 = (subsets ["second"; "first"] = [[]; ["first"]; ["second"]; ["second"; "first"]])
let test18 = (var_list (Id "test18") = ["test18"])
let test19 = (var_list (Const false) = [])
let test20 = (var_list (And (Id "test", Id "works")) = ["test"; "works"])
let test21 = (var_list (Or (Id "yes", Const false)) = ["yes"])
let test22 = (find_sat_sets (Or (Const false, Id "good")) = [["good"]])
let test23 = (find_sat_sets (Const true) = [[]])
let test24 = (find_sat_sets (And (Const true, Id "lets go")) = [["lets go"]])
let test25 = (find_sat_sets (Xor (Const false, Id "xor")) = [["xor"]])
